---
- block:
    - name: Ensure specified locales are present on RedHat 7 distributions
      command: >-
        localedef
        -i {{ item | langcode | quote }}
        -f {{ item | encoding | quote }}
        {{ item | encoding2lower | quote }}
      changed_when: false
      loop: "{{ localization_locales_present }}"

    - name: Ensure specified locales are absent on RedHat 7 distributions
      command: >-
        localedef
        --delete-from-archive {{ item | langcode | quote }}
        -f {{ item | encoding | quote }}
        {{ item | encoding2lower | quote }}
      changed_when: false
      loop: "{{ localization_locales_absent }}"
  # in RedHat 8 distributions the locales come pre-compiled with
  # 'glibc-langpack-<locale_code>' packages
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version <= 7

- block:
    - name: Ensure specified locales are present
      locale_gen:
        name: "{{ item }}"
        state: present
      loop: "{{ localization_locales_present }}"

    - name: Ensure specified locales are absent
      locale_gen:
        name: "{{ item }}"
        state: absent
      loop: "{{ localization_locales_absent }}"
  when: ansible_os_family != 'RedHat'

- name: Configure locales
  template:
    src: locale.conf.j2
    dest: "{{ localization_locales_conf }}"
    owner: root
    group: root
    mode: 0644
    lstrip_blocks: true
