---
- name: Include OS-specific variables
  tags: localization
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}.yml"
      skip: true

- name: Install requirements and language packs
  tags: localization
  package:
    name: "{{ localization_requirements + localization_language_packs }}"
    state: present

- import_tasks: timezone.yml
  tags: localization

- import_tasks: locales.yml
  tags: localization

- import_tasks: keymap.yml
  tags: localization
