---
- name: Include OS-specific variables
  tags: localization
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}_{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      skip: true

- name: Install requirements and language packs
  tags: [localization, localization_install]
  package:
    name: "{{ __localization_requirements + localization_language_packs }}"
    state: present

- import_tasks: timezone.yml
  tags: [localization, localization_timezone]

- import_tasks: locales.yml
  tags: [localization, localization_locales]

- import_tasks: keymap.yml
  tags: [localization, localization_keymap]
