---
- name: Ensure specified locales are present
  command: >-
    localedef
    -i {{ item|regex_replace('(.*)\\..*', '\\1') | quote }}
    -f {{ item|regex_replace('.*\\.(.*)', '\\1') | quote }} {{ item|quote }}
  changed_when: false
  loop: "{{ locales_present }}"

- name: Ensure specified locales are absent
  command: >-
    localedef
    --delete-from-archive {{ item|regex_replace('(.*)\\..*', '\\1') | quote }}
    -f {{ item|regex_replace('.*\\.(.*)', '\\1') | quote }} {{ item|quote }}
  changed_when: false
  loop: "{{ locales_absent }}"
