---
- name: Converge
  hosts: all
  vars:
    localization_locales_present:
      - de_DE.UTF-8
    localization_locales_absent:
      - en_US.UTF-8
    localization_locales_default:
      LANGUAGE: de_DE
      LANG: de_DE.UTF-8
      LC_ADDRESS: de_DE.UTF-8
      LC_COLLATE: de_DE.UTF-8
      LC_CTYPE: de_DE.UTF-8
      LC_IDENTIFICATION: de_DE.UTF-8
      LC_MONETARY: de_DE.UTF-8
      LC_MESSAGES: de_DE.UTF-8
      LC_MEASUREMENT: de_DE.UTF-8
      LC_NAME: de_DE.UTF-8
      LC_NUMERIC: de_DE.UTF-8
      LC_PAPER: de_DE.UTF-8
      LC_TELEPHONE: de_DE.UTF-8
      LC_TIME: de_DE.UTF-8
      # LC_ALL: de_DE.UTF-8
    localization_language_packs: "{{
      ['language-pack-de'] if ansible_distribution == 'Ubuntu' else
      ['glibc-langpack-de'] if ansible_os_family == 'RedHat' and ansible_distribution_major_version == '8' else
      []
    }}"
    localization_keymap: de
    localization_keymap_toggle: de-latin1
    localization_timezone: Europe/Berlin
  roles:
    - aisbergg.localization
