---
- name: Prepare ArchLinux Distributions
  hosts: archlinux
  gather_facts: no
  tasks:
    - name: Ensure Python is installed
      raw: pacman -Sy --noconfirm python
    - name: Ensure Python is installed
      raw: rm /etc/locale.gen
    - name: Reinstall glibc
      raw: pacman -S --noconfirm glibc grep

- name: Prepare Debian Distributions
  hosts: debian
  gather_facts: no
  tasks:
    - name: Update package cache
      raw: apt-get update
    - name: Ensure Python is installed
      raw: apt-get install -y python3

