---
- name: Prepare ArchLinux Distributions
  hosts: archlinux
  gather_facts: false
  tasks:
    - name: ensure Python is installed
      ansible.builtin.raw: pacman -Sy --noconfirm python
      changed_when: false
    - name: remove locale.gen file
      ansible.builtin.raw: rm /etc/locale.gen  # noqa deprecated-command-syntax
      changed_when: false
    - name: reinstall glibc
      ansible.builtin.raw: pacman -S --noconfirm glibc grep
      changed_when: false

- name: Prepare Debian Distributions
  hosts: debian
  gather_facts: false
  tasks:
    - name: update package cache
      ansible.builtin.raw: apt-get update
      changed_when: false
    - name: ensure Python is installed
      ansible.builtin.raw: apt-get install -y python3
      changed_when: false

- name: Prepare RedHat Distributions
  hosts: redhat
  gather_facts: false
  tasks:
    - name: ensure Python is installed
      ansible.builtin.raw: yum install -y python36
      changed_when: false
    - name: reinstall GlibC
      ansible.builtin.raw: sh -c "yum reinstall -y glibc || yum install -y glibc"
      changed_when: false
